version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=cloudFileStorage
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=SRplWb1Eq4Sfy37bbH1MnRqSHgpI3ew
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
          - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
    - ~/data/redis:/var/lib/redis
    - ~/data/redis/config:/usr/local/etc/redis/redis.conf

  minio:
    image: bitnami/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=spring
      - MINIO_ROOT_PASSWORD=R0dl9Dp29pr5CzQIJPC3dBrsC3u1nMHoug
    volumes:
      - /var/lib/minio/data:/var/lib/minio/data