spring:
  application:
    name: cloudFileStorage

  datasource:
    username: spring
    password: SRplWb1Eq4Sfy37bbH1MnRqSHgpI3ew
    url: jdbc:postgresql://localhost:5432/cloudFileStorage
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

app:
  countOfBytesToGenerateUserId: 5
