spring:
  application:
    name: cloudFileStorage

  datasource:
    username: spring
    password: SRplWb1Eq4Sfy37bbH1MnRqSHgpI3ew
    url: jdbc:postgresql://localhost:5432/cloudFileStorage
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  minio:
    client:
      endpoint: http://127.0.0.1:9000
      accessKey: spring
      secretKey: R0dl9Dp29pr5CzQIJPC3dBrsC3u1nMHoug
    bucket: user-data

app:
  countOfBytesToGenerateUserId: 5
  countBytesToGenerateObjectId: 8
  
springdoc:
  swagger-ui:
    url: /openapi/openapi.json
